= REST to SOAP Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-rest-to-soap/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-rest-to-soap/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Scope

|===
|onRequest |onResponse

| X
|

|===

== Description

REST to SOAP policy let you expose SOAP backend service as a REST API. The policy will pass the SOAP envelope message
to the backend service as POST request. SOAP envelope supports Expression Language to provide dynamic SOAP action.

For example, a SOAP API `http(s)://GATEWAY_HOST:GATEWAY_PORT/soap?countryName=France` with the following `rest-to-soap` policy SOAP envelope content :

[source=xml]
----
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope\\\" xmlns:web=\\\"http://www.oorsprong.org/websamples.countryinfo">
   <soap:Header/>
   <soap:Body>
      <web:CountryISOCode>
         <web:sCountryName>{#request.params['countryName']}</web:sCountryName>
      </web:CountryISOCode>
   </soap:Body>
</soap:Envelope>
----

Will give you the country ISO code of the `France` country.

== Configuration

You can configure the policy with the following options :

|===
|Property |Required |Description |Type |Default

|SOAP Envelope
|X
|
|SOAP envelope used to invoke WS (support Expression Language)
|

|SOAP Action
|
|
|'SOAPAction' HTTP header send when invoking WS
|

|Charset
|
|
|This charset will be appended to the Content-Type header value
|

|===


[source, json]
.Sample
----
"rest-to-soap": {
  "envelope": "<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:web="http://www.oorsprong.org/websamples.countryinfo">
                 <soap:Header/>
                 <soap:Body>
                    <web:ListOfCountryNamesByName/>
                 </soap:Body>
              </soap:Envelope>",
  "soapAction": null
}
----
